sudo: required
services:
  - docker

before_install:
  - docker build -t adburpitt/react-test -f ./client/Dockerfile.dev ./client
  # - docker build OTHER THING TO TEST
  
script:
  - docker run adburpitt/react-test npm test -- --coverage
  # - docker run OTHER THING TESTPLS

after_success:
  - docker build -t adburpitt/multi-client ./client
  - docker build -t adburpitt/multi-nginx ./nginx
  - docker build -t adburpitt/multi-server ./server
  - docker build -t adburpitt/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push adburpitt/multi-client
  - docker push adburpitt/multi-nginx
  - docker push adburpitt/multi-server
  - docker push adburpitt/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-754134521271
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY